### ISSUE TITLE
Library usage example is wrong

### ISSUE THREAD

**Issue by Lukas-Kullmann** [hiveeyes/dwdweather2#15]
The library usage example is wrong. It lacks the required parameter resolution is missing and the hour parameter of query was renamed.
It should be the following:

```diff
from datetime import datetime
from dwdweather import DwdWeather

# Create client object.
- dw = DwdWeather()
+ DW = DwdWeather(resolution="hourly") 

# Find closest station to position.
closest = dw.nearest_station(lon=7.0, lat=51.0)

# The hour you're interested in.
# The example is 2014-03-22 12:00 (UTC).
query_hour = datetime(2014, 3, 22, 12)

- result = dw.query(station_id=closest["station_id"], hour=query_hour) 
+ result = dw.query(closest["station_id"], query_hour)
print(result)
```

Took me several hours to figure that out. :/

**Comment by amotl** [comment]
Dear Lukas,

thanks for writing in and sorry for the hassle. We just fixed the usage example within README.rst.

With kind regards,
Andreas.

**Comment by Lukas-Kullmann** [comment]
That was fast, thank you! 🙂

**Comment by amotl** [comment]
Thanks again for bringing that up!
