### ISSUE TITLE
Float data mapped as int in Dataset

### ISSUE THREAD

**Issue by schmiddim** [hiveeyes/dwdweather2#19]
`Station "662" has no data for category "soil_temperature"
 50%|████████████████                | 271257/541989 [01:20<01:05, 4125.29it/s]Error in converting field 'solar_duration', value '118.0' to int.
  File "/home/xxxxxxx/.local/lib/python3.6/site-packages/dwdweather/core.py", line 469, in import_measures_textfile
    cell = int(cell)
`

**How to reproduce:**

```

from dwdweather import DwdWeather
from datetime import datetime

dw = DwdWeather(resolution="hourly")

dw.query(station_id=662, timestamp=datetime.now())
```

My Fix:
https://github.com/panodata/dwdweather2/pull/20

**Comment by amotl** [comment]
Merged #20. Thanks!
