### ISSUE TITLE
Forecast data

### ISSUE THREAD

**Issue by drmrbrewer** [hiveeyes/dwdweather2#2]
This looks promising, thanks!  From the code it appears to be fetching observations data.  Are there any plans to add functionality to access forecast data too?

**Comment by amotl** [comment]
Dear @drmrbrewer,

thanks for writing in.

> Are there any plans to add functionality to access forecast data too?

Sure! We will try to further improve this piece of software infrastructure- and feature-wise and will be happy to get support for doing so.

The power of [Luftdatenpumpe](https://github.com/hiveeyes/luftdatenpumpe) is kind of the reference of what we would like to achieve in the long run here, while definitively adding more DWD-specific things.

With kind regards,
Andreas.

**Comment by drmrbrewer** [comment]
Hi Andreas... OK, great!  Exciting times ahead...

**Comment by onlygecko** [comment]
Are there any concrete plans for including forecast data? I'm not a weather scientist, but from the technical point the dwd forecast data is available as a XML file (KML) for every station. What do You think?

**Comment by amotl** [comment]
Dear @onlygecko,

while supporting more things from DWD is still on our wishlist, we haven't been able to make more concrete plans about this. However, contributions are always welcome!

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @drmrbrewer and @onlygecko,

we just found out that [dwdbulk](https://github.com/jlewis91/dwdbulk) by @jlewis91 (thanks!) already supports acquisition of forecast data from DWD.

While it would be cool to merge functionalities of both projects as outlined within #22, the `dwdbulk` implementation might make you happy already.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @drmrbrewer and @onlygecko,

as [Wetterdienst](https://github.com/earthobservations/wetterdienst) will be the designated successor library for `dwdweather2`, it makes sense to add respective features there. In order to track this, I've recently created https://github.com/earthobservations/wetterdienst/issues/70, so I am deliberately closing the issue here.

With kind regards,
Andreas.
