### ISSUE TITLE
Daily Data

### ISSUE THREAD

**Issue by nickikaempf** [hiveeyes/dwdweather2#24]
Hi,

I am currently working with the dwdweather2 package and everything is working just fine. Thanks for the nice package!

What I want to get as a result is daily data from different stations. Until now, the package only supports hourly and 10-minutes resolution. Is it possible to add the daily data functionality to the package? Then I don't need to aggregate the data and that would save me a lot of time. 

The data is already available in [CDC](https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/).

Many thanks in advance.

**Comment by antjefitzner** [comment]
Would be interested in this feature as well!

**Comment by amotl** [comment]
Dear @nickikaempf and @antjefitzner,

the most recent version of `dwdweather2` now supports data acquisition from the `daily` resolution data set. I will be happy to hear about any outcome from you.

Happy hacking and with kind regards,
Andreas.

---

### Example
```
dwdweather weather 44 2020-06-01 --resolution daily
```

```
{
    "cloud_cover": null,
    "daily_quality_level_3": null,
    "daily_quality_level_4": 1,
    "datetime": 20200601,
    "humidity": 47.92,
    "precipitation_form": 0,
    "precipitation_height": 0.0,
    "pressure": null,
    "snow_depth": null,
    "soil_temperature_002": null,
    "soil_temperature_005": 21.7,
    "soil_temperature_010": 20.6,
    "soil_temperature_020": 19.0,
    "soil_temperature_050": 16.3,
    "soil_temperature_quality_level": 1,
    "solar_atmosphere": null,
    "solar_dhi": null,
    "solar_ghi": null,
    "solar_quality_level": null,
    "solar_sunshine": null,
    "station_id": 44,
    "sunshine_duration": 13.933,
    "temperature": 18.0,
    "temperature_max_200": 25.4,
    "temperature_min_005": 3.3,
    "temperature_min_200": 8.7,
    "vapor_pressure": 9.6,
    "wind_gust_max": null,
    "wind_velocity_mean": null
}
```

**Comment by antjefitzner** [comment]
Hi Andreas,

yes, it works :) Thanks a lot!

Cheers,
Antje

**Comment by amotl** [comment]
Hi Antje,

thanks for letting me know.

Cheers,
Andreas.
