### ISSUE TITLE
Getting data for a list of N closest stations

### ISSUE THREAD

**Issue by antjefitzner** [hiveeyes/dwdweather2#25]
Hi,

I want to get a list of the x nearest stations (and not just the closest). How can I do this? It seems in the command line this is possible, but I am using the library. Am I missing it or is it not possible yet?

Just some context: I want to get the e.g. 3 closest stations that have data for e.g. wind speed around a given point.

TIA
Antje

**Comment by amotl** [comment]
Dear Antje,

thanks for writing in. Your request sounds familiar. See also #3, #14 and #16 which might help you along. Please let me know about the outcome for you.

With kind regards,
Andreas.

**Comment by antjefitzner** [comment]
Hi Andreas,

my colleague actually looked it up in your code. Adding "surrounding" worked like:
```
closest_stations = dwd.nearest_station(lon=longitude, lat=latitude, surrounding=radius)
```

**Comment by amotl** [comment]
Dear Antje,

thanks! I also would like to note that [Wetterdienst](https://github.com/earthobservations/wetterdienst) also provides this feature through both https://github.com/earthobservations/wetterdienst/pull/23 and https://github.com/earthobservations/wetterdienst/pull/99.

With kind regards,
Andreas.

cc @JohannesRol, @stianchris, @ugur175, @meteoDaniel, @gutzbenj
