### ISSUE TITLE
Problem using categories on daily data

### ISSUE THREAD

**Issue by BenjaminMews** [hiveeyes/dwdweather2#27]
If I try to restrict the categories in library usage (daily resolution), no precipitation is found for any station. Without the restriction to category_names I can derive "precipitation_height" from results. Is that wanted behaviour or a bug?

**Comment by amotl** [comment]
Dear Benjamin,

thanks for writing in. There's an anomaly in categories correlating to resolutions. While the `precipitation` category will work on `hourly` and `10_minutes` resolutions, the appropriate category will be `daily_observations` for the `daily` resolution.

The background on this is that the baseline data of the `daily` resolution data set [1] is coming from the `kl` folder. Currently, we are ingesting data from the `kl`, `soil_temperature` and `solar` folders within [1], see also [2]. We haven't touched the `more_precip`, `water_equiv` and `weather_phenomena` folders yet.

I've actually expected people to run into this issue but haven't had the chance to document this appropriately yet. Sorry for that!

With kind regards,
Andreas.

[1] https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/
[2] https://github.com/panodata/dwdweather2/blob/0.13.0/dwdweather/knowledge.py#L58-L243

---

### Example
```
dwdweather weather 44 2020-06-04 --resolution daily --categories daily_observations --reset-cache
```

```
"precipitation_form": 4,
"precipitation_height": 8.8,
```

**Comment by amotl** [comment]
Dear @BenjaminMews,

[Wetterdienst](https://github.com/earthobservations/wetterdienst) will be the designated successor library for `dwdweather2`. You might be interested to switch over.

Further, I am deliberately closing this issue. Feel free to reopen anytime.

With kind regards,
Andreas.

cc @gutzbenj

---

```
wetterdienst readings --resolution=daily --parameter=kl --period=recent --station=44
```
