### ISSUE TITLE
Differences in column names between macOS and Windows?

### ISSUE THREAD

**Issue by MarkusZehner** [hiveeyes/dwdweather2#28]
Hi,

i'm getting the older columnnames e.g. "soiltemp_temperature_005" when requesting data on macos. When running on windows, i get the newer "soil_temperature_005" for the same value. 

Is there a way to control which columnnames are used? 

thanks!

markus

**Comment by amotl** [comment]
Dear Markus,

we updated the field names just recently through 58f1a26c. After getting a fresh release on your macOS system (e.g. by invoking `pip install dwdweather2 --upgrade`), you should see the same set of column names to be used.

Cheers,
Andreas.

**Comment by MarkusZehner** [comment]
i found the error! 

the cache was not deleted when updating, so the names would not change. As i created that cache long ago this was still using the older column names.
