### ISSUE TITLE
Requests restricted

### ISSUE THREAD

**Issue by bmxp** [hiveeyes/dwdweather2#29]
When installing dwdweather2 I find ``dwdweather2 0.14.0 has requirement requests<2.23,>=2.22``

Is there a reason why requests 2.24.0 is banned?

**Comment by amotl** [comment]
Dear @bmxp,

I believe there is no particular reason to pin this to a specific version of the `requests` library. Please let me know if I should cut a new release relaxing the version pinning on this dependency.

However, I strongly recommend to move on to the [Wetterdienst](https://github.com/earthobservations/wetterdienst) package. It is the successor library to `dwdweather` and `dwdweather2` and is becoming more and more popular these days. We have been trying to get this en par with all the features offered by `dwdweather2` and we have come pretty far these days. Enjoy!

With kind regards,
Andreas.

cc @gutzbenj

**Comment by bmxp** [comment]
Thank you for your hint about Wetterdienst. It might be indeed the way to go. If you feel that **dwdweather2** is a kind of deprecated then there is no need for a change, otherwise a version with a more relaxed dependency on requests would be good, just to prevent incompatabilities when using this lib with other projects.

Thanks for your feedback,
kind regards, Bernd
