### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by jeremiahpslewis** [hiveeyes/dwdweather2#9]
Hey!

Just wanted to see if you would entertain adding Continuous Integration via Microsoft Azure. Looking to try out Azure Pipelines and would be happy to add this to the project.

e.g. https://azure.microsoft.com/en-in/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

**Comment by amotl** [comment]
Dear Jeremiah,

we like `pytest` and recently did some first steps with CircleCI on another project [1,2]. We would appreciate test coverage and continuous integration very much. While we've heard good things about Azure, we are a bit hesitant to decide for it. As we plan to put more of our projects onto CircleCI, we are humbly asking if this also would be a valid option for you?

With kind regards,
Andreas.

[1] https://circleci.com/gh/hiveeyes/grafana-worldmap-panel
[2] https://github.com/hiveeyes/grafana-worldmap-panel

**Comment by amotl** [comment]
This has been a home run [1]. Thanks!

[1] https://circleci.com/gh/hiveeyes/dwdweather2/2
